# Generated by Django 2.0.4 on 2018-05-16 07:31

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='价格')),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('eur', '欧元'), ('usd', '美元')], max_length=10, verbose_name='币种')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('type', models.CharField(choices=[('list_price', '面价'), ('deal', '成交价'), ('other', '其他')], max_length=20, verbose_name='价格种类')),
            ],
            options={
                'verbose_name': '价格',
                'verbose_name_plural': '价格',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_id', models.CharField(max_length=10, verbose_name='原厂商物料号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('desc', models.CharField(max_length=300, verbose_name='描述')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='图文描述')),
                ('type', models.CharField(choices=[('tool', '工具'), ('lug', '端子'), ('dies', '模具'), ('other', '其他')], max_length=10, verbose_name='种类')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Price', verbose_name='价格')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品价格',
                'verbose_name_plural': '产品价格',
            },
        ),
    ]
