# Generated by Django 2.0.4 on 2018-05-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=300, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=300, null=True, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('tool', '工具'), ('lug', '端子'), ('dies', '模具'), ('other', '其他')], default='other', max_length=10, verbose_name='种类'),
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
