# Generated by Django 2.0.4 on 2018-05-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180517_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='详细描述'),
        ),
    ]
