# Generated by Django 2.0.4 on 2018-05-28 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180517_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHasPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品定价',
                'verbose_name_plural': '产品定价',
            },
        ),
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.AddField(
            model_name='producthasprice',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Price', verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='producthasprice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product', verbose_name='产品'),
        ),
    ]
