# Generated by Django 2.0.4 on 2018-05-28 17:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180528_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.TextField(blank=True, verbose_name='地址')),
                ('type', models.CharField(choices=[('delivery', '交货地址'), ('contact', '联系地址'), ('other', '其他')], max_length=10, verbose_name='地址种类')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_status', models.CharField(choices=[('partial', '部分开票'), ('fully', '全部开票'), ('na', '还未开票')], default='na', max_length=10, verbose_name='是否开票')),
                ('order_type', models.CharField(choices=[('vendor', '供应商订单'), ('customer', '客户订单')], default='customer', max_length=10, verbose_name='订单类型')),
                ('payment_term', models.IntegerField(blank=True, default=60, verbose_name='付款周期')),
                ('due_date', models.DateField(blank=True, verbose_name='最迟付款日期')),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('eur', '欧元'), ('usd', '美元')], default='rmb', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='汇率')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='付款日期')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='单位数量')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='总价')),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('eur', '欧元'), ('usd', '美元')], default='rmb', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='汇率')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('partner_type', models.CharField(choices=[('vendor', '供应商'), ('customer', '客户')], default='customer', max_length=10, verbose_name='伙伴类型')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
                'db_table': 'partner',
            },
        ),
        migrations.AlterModelTable(
            name='price',
            table='price',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='producthasprice',
            table='product_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ProductHasPrice', verbose_name='单位价格'),
        ),
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Partner', verbose_name='合作伙伴'),
        ),
        migrations.AddField(
            model_name='address',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Partner', verbose_name='合作伙伴'),
        ),
    ]
