# Generated by Django 2.0.4 on 2018-05-29 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180528_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=10, verbose_name='发票号码')),
                ('invoice_type', models.CharField(choices=[('vendor', '供应商账单'), ('customer', '客户账单')], default='customer', max_length=10, verbose_name='发票对象')),
                ('is_vat', models.BooleanField(default=True, verbose_name='是否增票')),
                ('vat_rate', models.IntegerField(default=16, verbose_name='增票税率')),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('eur', '欧元'), ('usd', '美元')], default='rmb', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='汇率')),
                ('sum_in_rmb', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='人民币金额')),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_partial_invoice', models.BooleanField(default=False, verbose_name='部分发票')),
                ('currency', models.CharField(choices=[('rmb', '人民币'), ('eur', '欧元'), ('usd', '美元')], default='rmb', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=20, verbose_name='汇率')),
                ('sum_in_rmb', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='人民币金额')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Invoice', verbose_name='发票')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单发票',
                'verbose_name_plural': '订单发票',
                'db_table': 'order_invoice',
            },
        ),
    ]
